-- MySQL Script generated by MySQL Workbench
-- Tue Feb 22 11:03:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema liga
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema liga
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `liga` DEFAULT CHARACTER SET utf8 ;
USE `liga` ;

-- -----------------------------------------------------
-- Table `liga`.`equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `liga`.`equipo` (
  `CodEquipo` INT NOT NULL,
  `NombreEquipo` VARCHAR(45) NOT NULL,
  `DescripcionEquipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CodEquipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `liga`.`jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `liga`.`jugador` (
  `CodJugador` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(200) NOT NULL,
  `ArmaFavorita` VARCHAR(40) NOT NULL,
  `CodEquipo` INT NOT NULL,
  PRIMARY KEY (`CodJugador`),
  INDEX `fk_jugador_equipo_idx` (`CodEquipo` ASC) ,
  CONSTRAINT `fk_jugador_equipo`
    FOREIGN KEY (`CodEquipo`)
    REFERENCES `liga`.`equipo` (`CodEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
